# Generated by Django 5.0.4 on 2024-05-03 13:00

import martor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=martor.models.MartorField(blank=True, null=True),
        ),
    ]
