# Generated by Django 5.0.4 on 2024-05-10 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_published_post_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
    ]
